version: '3.4'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    expose:
      - 5435
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  dotnet-api:
    build: 
      context: ../dotNetLearn
      dockerfile: Dockerfile
    environment:
      FRONTEND_URL: 'http://localhost'
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+;http://+:8080'
      ASPNETCORE_HTTPS_PORT: 4443
      ASPNETCORE_Kestrel__Certificates__Default__Password: '1234'
      ASPNETCORE_Kestrel__Certificates__Default__Path: '/https/aspnetapp.pfx'
      DB_NOSSL: true
    ports:
      - '8080:8080'
      - '4443:443'
    volumes:
      - ${HOME}/.aspnet/https:/https/
  dotnet-api-tests:
    build: 
      context: ../dotNetLearn
      dockerfile: tests.Dockerfile.disable
  vue-frontend:
    build: 
      context: ../vueLearn
      dockerfile: Dockerfile
      args:
        - VITE=DOTNET_API=https://localhost:4443/,NODE_API=http://localhost:3030/
    ports:
      - '80:80'
  node-api:
    build: ../nodejsLearn
    environment:
      - DEBUG=*
    ports:
      - '3030:3030'
    expose:
      - '3030'