version: '3.4'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    expose:
      - 5435
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  dotnet-api:
    build: 
      context: ../dotNetLearn
      dockerfile: Dockerfile
    environment:
      FRONTEND_URL: 'http://localhost'
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+;http://+'
      ASPNETCORE_HTTPS_PORT: 4443
      ASPNETCORE_Kestrel__Certificates__Default__Password: '1234'
      ASPNETCORE_Kestrel__Certificates__Default__Path: '/https/aspnetapp.pfx'
    ports:
      - '8080:80'
      - '4443:443'
    volumes:
      - ${HOME}/.aspnet/https:/https/
  dotnet-api-tests:
    build: 
      context: ../dotNetLearn
      dockerfile: tests.Dockerfile
  vue-frontend:
    build: ../vueLearn
    ports:
      - '80:80'
  # node-api:
  #   image: mysql:8.0.28
  #   environment:
  #     MYSQL_DATABASE: 'super-app'
  #     MYSQL_ROOT_PASSWORD: '$SuperApp1'
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'