name: Deploy Vue frontend to GCP Cloud Storage

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '/vueLearn/dist'
        destination: '${{ secrets.GCP_VUE_BUCKET_NAME }}'
