name: Deploy DotNet API to GCP Cloud Run

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deployNET'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'dotnet-api'
        source: './dotNetLearn'
        region: 'europe-west1'
        secrets: |
          INSTANCE_CONNECTION_NAME=instance-name:latest
          DB_USER=pg-user:latest
          DB_PASS=pg-pass:latest
          DB_NAME=challenges-db-name:latest
#          /tmp/https/aspnetapp_pfx=aspnet-ssl-cert:latest
#          ASPNETCORE_Kestrel__Certificates__Default__Password=aspnet-ssl-cert-pass:latest
        env_vars: |
          FRONTEND_URL=http://localhost
          ASPNETCORE_ENVIRONMENT=Development
#          ASPNETCORE_URLS=http://+:8080
#          ASPNETCORE_HTTPS_PORT=443
#          ASPNETCORE_Kestrel__Certificates__Default__Path='/tmp/https/aspnetapp_pfx'
