name: Deploy Vue frontend to Azure Static Web App

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: vueLearn

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci && VITE_ARGS=$VITE npm run build-only
      env:
        VITE: DOTNET_API=https://dotnetapi.blacksky-27d70672.northeurope.azurecontainerapps.io/,NODE_API=https://nodejsapi.jollyisland-5593ab8e.northeurope.azurecontainerapps.io/

#   Deploy
    - uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FOREST_09E05D703 }}
        action: "upload"
        app_location: "vueLearn/dist"
        skip_app_build: true
